CREATE USER PRGMGTEST IDENTIFIED BY 12345;

GRANT CREATE SESSION TO PRGMGTEST;
GRANT CREATE DATABASE LINK TO PRGMGTEST;
GRANT CREATE MATERIALIZED VIEW TO PRGMGTEST;
GRANT CREATE PROCEDURE TO PRGMGTEST;
GRANT CREATE PUBLIC SYNONYM TO PRGMGTEST;
GRANT CREATE ROLE TO PRGMGTEST;
GRANT CREATE SEQUENCE TO PRGMGTEST;
GRANT CREATE SYNONYM TO PRGMGTEST;
GRANT CREATE TABLE TO PRGMGTEST;
GRANT DROP ANY TABLE TO PRGMGTEST;
GRANT CREATE TRIGGER TO PRGMGTEST;
GRANT CREATE TYPE TO PRGMGTEST;
GRANT CREATE VIEW TO PRGMGTEST;

----------------------------------------------------------------------------------
CREATE TABLE FL_CODE
(
    PJT_COMM_C VARCHAR2(2)  NOT NULL
        CONSTRAINT PK_FL_CODE
            PRIMARY KEY,
    PJT_DESC_C VARCHAR2(50) NOT NULL,
    PJT_YN_C   VARCHAR2(1)  NOT NULL
);

CREATE TABLE FL_PJT_CODE
(
    PJT_C     VARCHAR2(50) NOT NULL,
    PJT_DIV_C VARCHAR2(50) ,
    PJT_ST_C  VARCHAR2(50) ,
    PJT_ORG_C VARCHAR2(50) ,
    CONSTRAINT PK_EMPLOYEES
        PRIMARY KEY (PJT_C)
);

ALTER TABLE FL_PJT_CODE ADD CONSTRAINT UNQ_FL_PJT_CODE UNIQUE (PJT_DIV_C,PJT_ST_C,PJT_ORG_C);


CREATE TABLE FL_EMP_CODE
(
    PJT_LV_C  VARCHAR2(4) NOT NULL,
    PJT_POS_C VARCHAR2(4) NOT NULL,
    CONSTRAINT PK_FL_EMP_CODE
        PRIMARY KEY (PJT_LV_C, PJT_POS_C)
);

----------------------------------------------------------------------------------
create table FL_EMP
(
    EMP_NO        NUMBER        not null,
    EMP_NM        VARCHAR2(30)  not null,
    EMP_PW        VARCHAR2(100) not null,
    EMP_EMAIL     VARCHAR2(100) not null,
    EMP_PHONE_NO  VARCHAR2(30)  not null,
    EMP_EMER_NO   VARCHAR2(30)  not null,
    EMP_JOIN_DATE VARCHAR2(10)  not null,
    PJT_LV_C      VARCHAR2(4)   not null,
    PJT_POS_C     VARCHAR2(3)   not null,
    constraint PK_EMP
        primary key (EMP_NO, EMP_EMAIL)
);


CREATE TABLE FL_EMP_ADMIN
(
    EMP_NO            NUMBER        NOT NULL
        CONSTRAINT PK_FL_EMP_ADMIN
            PRIMARY KEY,
    EMP_EMAIL         VARCHAR2(100) NOT NULL,
    LOGIN_DATE        VARCHAR2(20),
    JOIN_DATE         VARCHAR2(20)  NOT NULL,
    US_CHANGE_PW_DATE VARCHAR2(20),
    LOGIN_FAIL_COUNT  NUMBER,
    LIST_ACCESS_DATE  VARCHAR2(10),
    PJT_DUTY_C        VARCHAR2(3),
    PJT_JG_C          VARCHAR2(3),
    EMP_AUTH          VARCHAR2(5)   NOT NULL,
    CONSTRAINT FK_FL_EMP_ADMIN
        FOREIGN KEY (EMP_NO, EMP_EMAIL) REFERENCES FL_EMP
);

CREATE TABLE FL_PROJECT
(
    PJT_C          VARCHAR2(50) NOT NULL
        CONSTRAINT PK_FL_PROJECT
            PRIMARY KEY,
    PJT_CLIENT     VARCHAR2(50) NOT NULL,
    PJT_NM         VARCHAR2(50) NOT NULL,
    PJT_EMP_LIST   VARCHAR2(80) NOT NULL,
    PJT_PM         VARCHAR2(50) NOT NULL,
    PJT_START_DATE VARCHAR2(50) NOT NULL,
    PJT_END_DATE   VARCHAR2(50) NOT NULL,
    PJT_END_YN     VARCHAR2(50) NOT NULL
);

CREATE TABLE FL_PJT_EMP_ADMIN
(
    PJT_C         VARCHAR2(11)  NOT NULL
        CONSTRAINT PK_FL_PJT_EMP_ADMINT
            PRIMARY KEY,
    EMP_NO        NUMBER        NOT NULL,
    EMP_EMAIL     VARCHAR2(100) NOT NULL,
    PJT_EMP_DIV_C VARCHAR2(3)   NOT NULL,
    EMP_NM        VARCHAR2(10)  NOT NULL,
    PJT_CMT_START VARCHAR2(10)  NOT NULL,
    PJT_CMT_PD    VARCHAR2(8)   NOT NULL
);


select * from FL_PROJECT;

sele